sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CMb4aNwRetAfZe7sSiqMYefgxI74+iH7Qam4WVpSzn6IvBwLefHiz0HaEDBGyhWwkOnQ/0saJI/XDlfETLl+Tdxm25ubqVDfV2LNHBcepntRvgF282lkjXREcaU3JeWEoD9NSXFiiGVxD3hDTV5bzKoTpSfWXNY5K1SPUnIWWMS4lXewj+Mqwy1NX3VWj0JQNMa1g7jHy2WtIhThw10TRYQaFhuzRVV/TB2nlkyGp5SuE9rZxk/5vMxrVYevA+MMrSlYtcyajevyImipq8ODXStsJ2dNpsj0yYkkkA4zpT802bW61gLhg7DMqMOs/kIJxhxVD/bJpC7AkKvgXRip73/hKqxzI1fHlSvPZXierASKFcdRfX1WnCY0xlAwBZnBO3QVyC0ygc5IThsTURpoQm5JUEUoUMs8NraC+zD1grr+ywwUhI2UPQx0tmu8RzWOcWyWNO0c/XQW6iB3IyP85NSx3tV3dw7U9Dj4QF/AD+8/dRDr2Ut14collDygQ+luE3YQQFTfaQmyUIWbMjJMeVx+e6UNMIfbgCjL3BjQq533LnPEwknSoKilszW42aUhlloCUmzmWCKw1j34hAMAz4suoCxf8TOAr1argkCb71eAVneWPsMGdiF3Xg0eRyZh9vQ5BIiQesgV8C5HZzrP1lIqDkScSLZN4Mfh1jxE7Ss=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-City-of-Domes-a-walk-with-an-architect-about-the-courts-and-palaces-of-the-Panama-Pacific-__3151
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy